### ISSUE TITLE
bpf verifier error

### ISSUE THREAD

**Issue by williamtu** [williamtu/p4c-ovs-ebpf#4]
The patch fixes the verifier error due to skb->data and data_end checking.
We have to follow the way verifier checking the packet boundary 
if (data + offset > data_end) ...
With this patch, I test TCP parsing and works OK. However, I also mark out the parse_vlan and parse_ipv6. I still don't know why they cause verifier failed.
[p4-xdp1.diff.txt](https://github.com/williamtu/p4c-ovs-ebpf/files/700628/p4-xdp1.diff.txt)

**Comment by williamtu** [comment]
following the above, when enable parse_vlan, error shows as below
 R0=imm1,min_value=1,max_value=1 R1=pkt(id=0,off=0,r=16) R2=pkt_end R3=pkt(id=0,off=16,r=16) R4=imm0,min_value=0,max_value=0 R5=imm112,min_value=112,max_value=112 R10=fp
32: (b7) r5 = 144
33: (69) r3 = *(u16 *)(r3 +0)
invalid access to packet, off=16 size=2, R3(id=0,off=16,r=16)

to enable debug info, at kernel/samples/Makefile
@@ -155,4 +155,4 @@ $(obj)/%.o: $(src)/%.c
        $(CLANG) $(NOSTDINC_FLAGS) $(LINUXINCLUDE) $(EXTRA_CFLAGS) \
                -D__KERNEL__ -D__ASM_SYSREG_H -Wno-unused-value -Wno-pointer-sign \
                -Wno-compare-distinct-pointer-types \
-               -O2 -emit-llvm -c $< -o -| $(LLC) -march=bpf -filetype=obj -o $@
+               -O2 -emit-llvm -g -c $< -o -| $(LLC) -march=bpf -filetype=obj -o $@

root@osboxes:~/net-next/samples/bpf# llvm-objdump -S -no-show-raw-insn xdp1_kern.o
; hdr.vlan.etherType = (u16)((load_half(((void*)(long)skb->data), BYTES(ebpf_packetOffsetInBits))));
      33:	r3 = *(u16 *)(r3 + 0)
; switch (hdr.vlan.etherType) {
      34:	bswap16	r3
      35:	if r3 == 2048 goto 111
      36:	if r3 == 2054 goto 222
      37:	if r3 != 34525 goto 249
; if (data_end < data + BYTES(ebpf_packetOffsetInBits + 8)) {

**Comment by mbudiu-vmw** [comment]
I have made some fixes, but I haven't figured out what's wrong with VLAN.

**Comment by williamtu** [comment]
thanks! I've posted the issue at 
https://lists.iovisor.org/pipermail/iovisor-dev/2017-January/000603.html
https://lists.iovisor.org/pipermail/iovisor-dev/2017-January/000604.html

**Comment by mbudiu-vmw** [comment]
Yes, I am very puzzled why the verifier rejects this program.
It is upset by this read:

hdr.vlan.etherType = (u16)((load_half(((void*)(long)skb->data), BYTES(ebpf_packetOffsetInBits))));

This is an aligned read of 16 bits. Very strange.

**Comment by mbudiu-vmw** [comment]
Have you managed to solve this problem?

**Comment by williamtu** [comment]
no...

**Comment by williamtu** [comment]
some updates.
https://lists.iovisor.org/pipermail/iovisor-dev/2017-January/000610.html

**Comment by williamtu** [comment]
Daniel will submit patch to net-next.
