### ISSUE TITLE
duplicate SEC in ebpf C file when using p4c-xdp

### ISSUE THREAD

**Issue by williamtu** [williamtu/p4c-ovs-ebpf#8]
when testing the latest with p4c-xdp, the generated C code has:
```C
SEC("ebpf_filter")
SEC("prog")
int ebpf_filter(struct xdp_md* skb){
    struct Headers_t headers = { 
        .ethernet = { 
```
maybe we should allow users to specify the SEC name, for example
```bash
./p4c-xdp --target xdp --sec <mysection name> -o <in> src.p4
```
if not, I'd prefer using "prog" since it is default in ip tool.

**Comment by mbudiu-vmw** [comment]
Let's keep it to a minimum of configuration options for now, we'll improve usability later.
I will keep it to "prog" for now.
